// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUmTtsq0A-5ULxEtyU7F3Hx8s7r3ea6tI',
    appId: '1:325272333412:android:bd3126ce1baef7bf508371',
    messagingSenderId: '325272333412',
    projectId: 'my-payment-app-2026',
    storageBucket: 'my-payment-app-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBD9ofIQjlWB8jxrgo3Zel3Qe3JqvUobME',
    appId: '1:325272333412:ios:8ccdd92989146b00508371',
    messagingSenderId: '325272333412',
    projectId: 'my-payment-app-2026',
    storageBucket: 'my-payment-app-2026.firebasestorage.app',
    iosBundleId: 'com.example.paymentTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBD9ofIQjlWB8jxrgo3Zel3Qe3JqvUobME',
    appId: '1:325272333412:ios:8ccdd92989146b00508371',
    messagingSenderId: '325272333412',
    projectId: 'my-payment-app-2026',
    storageBucket: 'my-payment-app-2026.firebasestorage.app',
    iosBundleId: 'com.example.paymentTracker',
  );
}
